name: Build and Deploy React/Python/Discord Solution to Azure Web App - theoraclegpt-dev

on:
  push:
    branches:
      - main-dev
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Stage Source Repository
        uses: actions/checkout@v4

      - name: Vite Build React Web App
        run: |
          cd frontend
          npm ci
          npm run lint
          npm run build

      - name: Stage React Web App
        run: |
          mkdir -p backend/static/
          [ -d frontend/dist ] && cp -r frontend/dist/* backend/static/

      - name: Install Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Python Dependencies
        run: |
          cd backend
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Package Python and React Web App
        run: |
          cd backend
          zip ../release.zip ./* -r -x "venv/*"

      - name: Stage Release Package
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download Release Package
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Extract Python and React Web App
        run: unzip release.zip

      - name: Runnger Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_F80996D78F45480CB170C45663222B39 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B837A10399AF45CAA4086839CAF42337 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_485F50803011479598534411A5F62B1E }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'theoraclegpt-dev'
          slot-name: 'Production'
