name: Build and Deploy React/Python/Discord Solution to Azure Web App - theoraclegpt

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Stage Source Repository
        uses: actions/checkout@v4

      - name: Install Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Vite Build React Web App
        run: |
          cd frontend
          npm ci
          npm run lint
          npm run build

      - name: Stage React Web App
        run: |
          mkdir -p backend/static/
          [ -d frontend/dist ] && cp -r frontend/dist/* backend/static/

      - name: Install Python Dependencies
        run: |
          cd backend
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Package Python and React Web App
        run: |
          cd backend
          zip ../release.zip ./* -r -x "venv/*"

      - name: Stage Release Package
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip



  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download Release Package
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Extract Python and React Web App
        run: unzip release.zip

      
      - name: Runner Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_19A5CD2BF942480A969049E5E896F3CB }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_1789AE929E07449B91C5950F2AB64C55 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_CB3B6EBD7831431C8DB5449FA89F8F55 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'theoraclegpt'
          slot-name: 'Production'
          
